version: "3.9"

services:
  pub_sub:
    container_name: pub_sub
    build:
      context: .
    environment:
      PUBSUB_PROJECT_ID: ${PUBSUB_PROJECT_ID}
      PUBSUB_EMULATOR_HOST: 0.0.0.0:8085
    restart: on-failure
    ports:
      - 8085:8085
    volumes:
      - ./volumes/pub-sub:/opt/data
    networks:
      - gcp

networks:
  gcp:
    driver: bridge
